/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import control.Control;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import java.text.ParseException;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author IVI
 */
public class JfrmPrincipal extends javax.swing.JFrame {
private Control control;
    /**
     * Creates new form JfrmPrincipal
     */
    public JfrmPrincipal() {
      try {
            UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
        } catch (ParseException | UnsupportedLookAndFeelException e) {
        }    
        
        initComponents();
        this.control=new Control();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuDatosescuela = new javax.swing.JMenu();
        subMenuDatosEscuela_AgregarCarrera = new javax.swing.JMenuItem();
        menuDatosAlumnos = new javax.swing.JMenu();
        subDatosAlumnos_AgregarAlumno = new javax.swing.JMenu();
        opcionMenuAgregarAlumno_Alumno = new javax.swing.JMenuItem();
        opcionMenuAgregarAlumno_AlumnoCarrera = new javax.swing.JMenuItem();
        subDatosAlumnos_AgregarPagos = new javax.swing.JMenu();
        opcionMenuAgregarPagos_Pagos = new javax.swing.JMenuItem();
        subMenuAgregarAdeudos = new javax.swing.JMenu();
        menuOpcionAgregarAdeudo_Adeudos = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        subMenuDatosAlumnos_AgregarGrupos = new javax.swing.JMenuItem();
        menuDatosCatalogo = new javax.swing.JMenu();
        submenuDatosCatalogo_AgregarCatalogo = new javax.swing.JMenu();
        opcionMenuCatalogo = new javax.swing.JMenuItem();
        subDatosCatalog_ActualizaCatalogo = new javax.swing.JMenu();
        opcionMenuActualizaCatalogo = new javax.swing.JMenuItem();
        subMenuDatosCatalogos_ConsultarCatalogo = new javax.swing.JMenu();
        opcionMenuConsultarCatalogo = new javax.swing.JMenuItem();
        menuDatosMaestros = new javax.swing.JMenu();
        subMenuDatosMaestros_AgregarMaestro = new javax.swing.JMenu();
        opcionMenuAgregaMaestro_AgregarMAestro = new javax.swing.JMenuItem();
        menuDatosMaterias = new javax.swing.JMenu();
        subDatosMateria_AgregarMateria = new javax.swing.JMenu();
        opcionMenuAgregarMateria_AgregarMAteria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        jMenuBar1.setEnabled(false);

        menuDatosescuela.setText("DatosEscuela");

        subMenuDatosEscuela_AgregarCarrera.setText("Agregar Carrera");
        subMenuDatosEscuela_AgregarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuDatosEscuela_AgregarCarreraActionPerformed(evt);
            }
        });
        menuDatosescuela.add(subMenuDatosEscuela_AgregarCarrera);

        jMenuBar1.add(menuDatosescuela);

        menuDatosAlumnos.setText("DatosAlumnos");

        subDatosAlumnos_AgregarAlumno.setText("Agregar Alumno");

        opcionMenuAgregarAlumno_Alumno.setText("Alumno");
        opcionMenuAgregarAlumno_Alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuAgregarAlumno_AlumnoActionPerformed(evt);
            }
        });
        subDatosAlumnos_AgregarAlumno.add(opcionMenuAgregarAlumno_Alumno);

        opcionMenuAgregarAlumno_AlumnoCarrera.setText("Alumno Carrera");
        opcionMenuAgregarAlumno_AlumnoCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuAgregarAlumno_AlumnoCarreraActionPerformed(evt);
            }
        });
        subDatosAlumnos_AgregarAlumno.add(opcionMenuAgregarAlumno_AlumnoCarrera);

        menuDatosAlumnos.add(subDatosAlumnos_AgregarAlumno);

        subDatosAlumnos_AgregarPagos.setText("Agregar Pagos");

        opcionMenuAgregarPagos_Pagos.setText("Pagos");
        opcionMenuAgregarPagos_Pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuAgregarPagos_PagosActionPerformed(evt);
            }
        });
        subDatosAlumnos_AgregarPagos.add(opcionMenuAgregarPagos_Pagos);

        menuDatosAlumnos.add(subDatosAlumnos_AgregarPagos);

        subMenuAgregarAdeudos.setText("Agregar Adeudos");

        menuOpcionAgregarAdeudo_Adeudos.setText("Adeudos");
        menuOpcionAgregarAdeudo_Adeudos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcionAgregarAdeudo_AdeudosActionPerformed(evt);
            }
        });
        subMenuAgregarAdeudos.add(menuOpcionAgregarAdeudo_Adeudos);

        menuDatosAlumnos.add(subMenuAgregarAdeudos);

        jMenu6.setText("Agregar  Grupos");

        subMenuDatosAlumnos_AgregarGrupos.setText("Grupo");
        subMenuDatosAlumnos_AgregarGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuDatosAlumnos_AgregarGruposActionPerformed(evt);
            }
        });
        jMenu6.add(subMenuDatosAlumnos_AgregarGrupos);

        menuDatosAlumnos.add(jMenu6);

        jMenuBar1.add(menuDatosAlumnos);

        menuDatosCatalogo.setText("DatosCatalogo");

        submenuDatosCatalogo_AgregarCatalogo.setText("Agregar Catalogo");

        opcionMenuCatalogo.setText("Catalogo");
        opcionMenuCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuCatalogoActionPerformed(evt);
            }
        });
        submenuDatosCatalogo_AgregarCatalogo.add(opcionMenuCatalogo);

        menuDatosCatalogo.add(submenuDatosCatalogo_AgregarCatalogo);

        subDatosCatalog_ActualizaCatalogo.setText("Actualiza Catalogo");

        opcionMenuActualizaCatalogo.setText("ActualizaCatalogo");
        opcionMenuActualizaCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuActualizaCatalogoActionPerformed(evt);
            }
        });
        subDatosCatalog_ActualizaCatalogo.add(opcionMenuActualizaCatalogo);

        menuDatosCatalogo.add(subDatosCatalog_ActualizaCatalogo);

        subMenuDatosCatalogos_ConsultarCatalogo.setText("Consultar Catalogo");

        opcionMenuConsultarCatalogo.setText("Consultar Catalogo");
        opcionMenuConsultarCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuConsultarCatalogoActionPerformed(evt);
            }
        });
        subMenuDatosCatalogos_ConsultarCatalogo.add(opcionMenuConsultarCatalogo);

        menuDatosCatalogo.add(subMenuDatosCatalogos_ConsultarCatalogo);

        jMenuBar1.add(menuDatosCatalogo);

        menuDatosMaestros.setText("DatosMaestros");

        subMenuDatosMaestros_AgregarMaestro.setText("Agrega Maestro");

        opcionMenuAgregaMaestro_AgregarMAestro.setText("Agregar Maestro");
        opcionMenuAgregaMaestro_AgregarMAestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuAgregaMaestro_AgregarMAestroActionPerformed(evt);
            }
        });
        subMenuDatosMaestros_AgregarMaestro.add(opcionMenuAgregaMaestro_AgregarMAestro);

        menuDatosMaestros.add(subMenuDatosMaestros_AgregarMaestro);

        jMenuBar1.add(menuDatosMaestros);

        menuDatosMaterias.setText("DatosMaterias");

        subDatosMateria_AgregarMateria.setText("Agregar Materia");

        opcionMenuAgregarMateria_AgregarMAteria.setText("Agregar Materia");
        opcionMenuAgregarMateria_AgregarMAteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuAgregarMateria_AgregarMAteriaActionPerformed(evt);
            }
        });
        subDatosMateria_AgregarMateria.add(opcionMenuAgregarMateria_AgregarMAteria);

        menuDatosMaterias.add(subDatosMateria_AgregarMateria);

        jMenuBar1.add(menuDatosMaterias);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subMenuDatosEscuela_AgregarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuDatosEscuela_AgregarCarreraActionPerformed
    try {
        // TODO add your handling code here:
        if(control.AgregarCarrera(this)){
            
        }
    } catch (Exception ex) {
        Logger.getLogger(JfrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_subMenuDatosEscuela_AgregarCarreraActionPerformed

    private void opcionMenuAgregarAlumno_AlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuAgregarAlumno_AlumnoActionPerformed
    try {
        // TODO add your handling code here:
        if(control.AgregarAlumno(this)){
            
        }
    } catch (Exception ex) {
        Logger.getLogger(JfrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_opcionMenuAgregarAlumno_AlumnoActionPerformed

    private void opcionMenuAgregarAlumno_AlumnoCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuAgregarAlumno_AlumnoCarreraActionPerformed
    try {
        // TODO add your handling code here:
        if(control.AgregarAlumnoCarrera(this)){
            
        }
    } catch (Exception ex) {
        Logger.getLogger(JfrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_opcionMenuAgregarAlumno_AlumnoCarreraActionPerformed

    private void opcionMenuAgregarPagos_PagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuAgregarPagos_PagosActionPerformed
    try {
        // TODO add your handling code here:
        if(control.agregarPago(this)){
            
        }
    } catch (Exception ex) {
        Logger.getLogger(JfrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_opcionMenuAgregarPagos_PagosActionPerformed

    private void menuOpcionAgregarAdeudo_AdeudosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcionAgregarAdeudo_AdeudosActionPerformed
    try {
        // TODO add your handling code here:
        if(control.agregarDeuda(this)){
            
        }
    } catch (Exception ex) {
        Logger.getLogger(JfrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_menuOpcionAgregarAdeudo_AdeudosActionPerformed

    private void subMenuDatosAlumnos_AgregarGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuDatosAlumnos_AgregarGruposActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_subMenuDatosAlumnos_AgregarGruposActionPerformed

    private void opcionMenuCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuCatalogoActionPerformed
    try {
        // TODO add your handling code here:
        if(control.AgregaCatalogo(this)){
            
        }
    } catch (Exception ex) {
        Logger.getLogger(JfrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_opcionMenuCatalogoActionPerformed

    private void opcionMenuAgregaMaestro_AgregarMAestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuAgregaMaestro_AgregarMAestroActionPerformed
    try {
        // TODO add your handling code here:
        if(control.AgregaMaestro(this)){
            
        }
    } catch (Exception ex) {
        Logger.getLogger(JfrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_opcionMenuAgregaMaestro_AgregarMAestroActionPerformed

    private void opcionMenuAgregarMateria_AgregarMAteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuAgregarMateria_AgregarMAteriaActionPerformed
    try {
        // TODO add your handling code here:
        if(!control.AgregaMateria(this)) {
        } 
    } catch (Exception ex) {
        Logger.getLogger(JfrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_opcionMenuAgregarMateria_AgregarMAteriaActionPerformed

    private void opcionMenuActualizaCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuActualizaCatalogoActionPerformed
    try {
        // TODO add your handling code here:
        if(control.actualizaCatalogo(this)){
            
        }
    } catch (Exception ex) {
        Logger.getLogger(JfrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_opcionMenuActualizaCatalogoActionPerformed

    private void opcionMenuConsultarCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuConsultarCatalogoActionPerformed
        // TODO add your handling code here:
        control.consultaCatalogo(this);
        
    }//GEN-LAST:event_opcionMenuConsultarCatalogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuDatosAlumnos;
    private javax.swing.JMenu menuDatosCatalogo;
    private javax.swing.JMenu menuDatosMaestros;
    private javax.swing.JMenu menuDatosMaterias;
    private javax.swing.JMenu menuDatosescuela;
    private javax.swing.JMenuItem menuOpcionAgregarAdeudo_Adeudos;
    private javax.swing.JMenuItem opcionMenuActualizaCatalogo;
    private javax.swing.JMenuItem opcionMenuAgregaMaestro_AgregarMAestro;
    private javax.swing.JMenuItem opcionMenuAgregarAlumno_Alumno;
    private javax.swing.JMenuItem opcionMenuAgregarAlumno_AlumnoCarrera;
    private javax.swing.JMenuItem opcionMenuAgregarMateria_AgregarMAteria;
    private javax.swing.JMenuItem opcionMenuAgregarPagos_Pagos;
    private javax.swing.JMenuItem opcionMenuCatalogo;
    private javax.swing.JMenuItem opcionMenuConsultarCatalogo;
    private javax.swing.JMenu subDatosAlumnos_AgregarAlumno;
    private javax.swing.JMenu subDatosAlumnos_AgregarPagos;
    private javax.swing.JMenu subDatosCatalog_ActualizaCatalogo;
    private javax.swing.JMenu subDatosMateria_AgregarMateria;
    private javax.swing.JMenu subMenuAgregarAdeudos;
    private javax.swing.JMenuItem subMenuDatosAlumnos_AgregarGrupos;
    private javax.swing.JMenu subMenuDatosCatalogos_ConsultarCatalogo;
    private javax.swing.JMenuItem subMenuDatosEscuela_AgregarCarrera;
    private javax.swing.JMenu subMenuDatosMaestros_AgregarMaestro;
    private javax.swing.JMenu submenuDatosCatalogo_AgregarCatalogo;
    // End of variables declaration//GEN-END:variables
}
