/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import control.ConstantesGUI;
import java.awt.Color;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import objetosNegocio.Catalogo;
import objetosNegocio.Maestro;
import objetosNegocio.Materia;

/**
 *
 * @author IVI
 */
public class DlgCatalogo extends javax.swing.JDialog {

    private Catalogo catalogo;
    private StringBuffer respuesta;
    private int operacion;

    /**
     * Creates new form JdlgCatalogo
     */
    public DlgCatalogo(java.awt.Frame parent, boolean modal, Catalogo catalogo, StringBuffer respuesta, int operacion) {
        super(parent, modal);
        initComponents();

        this.catalogo = catalogo;
        this.respuesta = respuesta;
        this.operacion = operacion;

        if (operacion == ConstantesGUI.AGREGAR) {
            this.txtId.setText(catalogo.getIdCatalogo() + "");
            this.txtId.setBackground(Color.GRAY);
            this.txtId.setEditable(false);

            this.txtMateria.setText("");
            this.txtMateria.setBackground(Color.GRAY);
            this.txtMateria.setEditable(false);

            this.txtMaestro.setText("");
            this.txtMaestro.setBackground(Color.GRAY);
            this.txtMaestro.setEditable(false);

        }
        if (operacion == ConstantesGUI.ACTUALIZAR) {
            Materia materia = catalogo.getIdMateriaFK();
            Maestro maestro = catalogo.getIdMaestroFK();
            this.txtId.setText(catalogo.getIdCatalogo() + "");
            this.txtId.setBackground(Color.GRAY);
            this.txtId.setEditable(false);

            if (materia != null) {
                this.txtMateria.setText(materia.getNombre());
                this.txtMateria.setBackground(Color.GRAY);
                this.txtMateria.setEditable(false);
            } else {
                this.txtMateria.setText("");
                this.txtMateria.setBackground(Color.GRAY);
                this.txtMateria.setEditable(false);
            }

            if (maestro != null) {
                this.txtMaestro.setText(maestro.getNombre());
                this.txtMaestro.setBackground(Color.GRAY);
                this.txtMaestro.setEditable(false);
            } else {
                this.txtMaestro.setText("");
                this.txtMaestro.setBackground(Color.GRAY);
                this.txtMaestro.setEditable(false);
            }
        }

        // en caso de que la operacion sea de desplegar  el catalogo o de eliminar
        // definimos el comportamiento iniial
        if (operacion == ConstantesGUI.DESPLEGAR || operacion == ConstantesGUI.ELIMINAR) {
            Maestro maestro = null;
            Materia materia = null;

            this.txtId.setText(catalogo.getIdCatalogo() + "");
            this.txtId.setBackground(Color.GRAY);
            this.txtId.setEditable(false);

            this.txtHora.setText(catalogo.getHora());
            this.txtHora.setBackground(Color.GRAY);
            this.txtHora.setEditable(false);

            this.txtAula.setText(catalogo.getAula());
            this.txtAula.setBackground(Color.GRAY);
            this.txtAula.setEditable(false);

            this.JcboxPeriodo.setVisible(false);
            this.jlbMensaje.setText("Actual mente Periodo; \n" + catalogo.getPerior());

            maestro = this.catalogo.getIdMaestroFK();
            materia = this.catalogo.getIdMateriaFK();

            if (maestro != null) {
                this.txtMaestro.setText(maestro.getNombre());
                this.txtMaestro.setBackground(Color.GRAY);
                this.txtMaestro.setEditable(false);
            } else {
                this.txtMaestro.setBackground(Color.GRAY);
                this.txtMaestro.setEditable(false);
            }
            
            if (materia != null) {
                this.txtMateria.setText(materia.getNombre());
                this.txtMateria.setBackground(Color.GRAY);
                this.txtMateria.setEditable(false);
            } else {
                this.txtMateria.setBackground(Color.GRAY);
                this.txtMateria.setEditable(false);
            }

        }

        this.respuesta.delete(0, respuesta.length());
        this.respuesta.append(ConstantesGUI.CANCELAR);
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtMateria = new javax.swing.JTextField();
        txtMaestro = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtAula = new javax.swing.JTextField();
        JcboxPeriodo = new javax.swing.JComboBox();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jlbMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("DI ");

        jLabel2.setText("Materia");

        jLabel3.setText("Maestro");

        jLabel4.setText("Hora");

        jLabel5.setText("Aula");

        jLabel6.setText("Period");

        txtId.setText(" ");

        txtMateria.setText(" ");

        txtMaestro.setText(" ");

        txtHora.setText(" ");

        txtAula.setText(" ");

        JcboxPeriodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Opciones", "Ener-Mayo", "Agosto- Novimenbre" }));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jlbMensaje.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaestro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAula, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(txtHora))
                            .addComponent(JcboxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnAceptar)
                        .addGap(87, 87, 87)
                        .addComponent(btnCancelar)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JcboxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        boolean ejecutar = true;
        if (operacion == ConstantesGUI.AGREGAR || operacion == ConstantesGUI.ACTUALIZAR) {
            catalogo.setAula(this.txtAula.getText());
            catalogo.setHora(this.txtHora.getText().trim().trim());
            String periodo = (String) this.JcboxPeriodo.getSelectedItem();

            if (periodo.equals("Opciones")) {
                ejecutar = false;
                this.JcboxPeriodo.setBackground(Color.red);
            }
            catalogo.setPerior(periodo);

            if (this.txtAula.getText().trim() == null) {
                ejecutar = false;
                this.txtAula.setBackground(Color.red);
            }
            if (this.txtHora.getText().trim().trim() == null) {
                ejecutar = false;
                this.txtHora.setBackground(Color.red);
            }

        }

        if (operacion == ConstantesGUI.DESPLEGAR || operacion == ConstantesGUI.ELIMINAR) {
            ejecutar = true;
        }
        if (ejecutar) {
            this.respuesta.delete(0, respuesta.length());
            this.respuesta.append(ConstantesGUI.ACEPTAR);
            this.dispose();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:

        this.respuesta.delete(0, respuesta.length());
        this.respuesta.append(ConstantesGUI.CANCELAR);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JcboxPeriodo;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jlbMensaje;
    private javax.swing.JTextField txtAula;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMaestro;
    private javax.swing.JTextField txtMateria;
    // End of variables declaration//GEN-END:variables
}
